# Generated by Django 4.2.10 on 2024-03-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_post_options_remove_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('genre', models.CharField(max_length=32)),
                ('developer', models.CharField(max_length=32)),
                ('publisher', models.CharField(max_length=32)),
                ('release', models.DateField()),
            ],
        ),
    ]
