# Generated by Django 4.2.10 on 2024-03-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='console',
            field=models.IntegerField(choices=[(0, ''), (1, 'Xbox series X|S'), (2, 'Playstation 5'), (3, 'Nintendo Switch')], default=0),
        ),
    ]
