# Generated by Django 4.2.10 on 2024-03-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_game_console'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='console',
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.IntegerField(choices=[(0, ''), (1, 'Xbox'), (2, 'Playstation'), (3, 'Nintendo')], default=0),
        ),
    ]
