# Generated by Django 4.2.10 on 2024-03-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_game_console_game_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='age_rating',
            field=models.IntegerField(null=True),
        ),
    ]
