# Generated by Django 4.2.10 on 2024-04-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_post_intro_alter_game_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
