# Generated by Django 4.2.10 on 2024-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_game_slug_alter_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=4096, null=True),
        ),
    ]
